name: Deploy to Vercel Staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Staging Deploy
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.VERCEL_MOVIE_TOKEN }}" \
            ${{ secrets.VERCEL_STAGING_HOOK }}
